/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CreateRouteImport } from './routes/create'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as JoinRouteImport } from './routes/join'
import { Route as RoomRoomIdRouteImport } from './routes/room.$roomId'
import { Route as ApiPublicHooksCleanupRouteImport } from './routes/api/public/hooks/cleanup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdRoute = RoomRoomIdRouteImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCleanupRoute = ApiPublicHooksCleanupRouteImport.update({
  id: '/api/public/hooks/cleanup',
  path: '/api/public/hooks/cleanup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create': typeof CreateRoute
  '/how-it-works': typeof HowItWorksRoute
  '/join': typeof JoinRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/api/public/hooks/cleanup': typeof ApiPublicHooksCleanupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create': typeof CreateRoute
  '/how-it-works': typeof HowItWorksRoute
  '/join': typeof JoinRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/api/public/hooks/cleanup': typeof ApiPublicHooksCleanupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create': typeof CreateRoute
  '/how-it-works': typeof HowItWorksRoute
  '/join': typeof JoinRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/api/public/hooks/cleanup': typeof ApiPublicHooksCleanupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/create'
    | '/how-it-works'
    | '/join'
    | '/room/$roomId'
    | '/api/public/hooks/cleanup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/create'
    | '/how-it-works'
    | '/join'
    | '/room/$roomId'
    | '/api/public/hooks/cleanup'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/create'
    | '/how-it-works'
    | '/join'
    | '/room/$roomId'
    | '/api/public/hooks/cleanup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CreateRoute: typeof CreateRoute
  HowItWorksRoute: typeof HowItWorksRoute
  JoinRoute: typeof JoinRoute
  RoomRoomIdRoute: typeof RoomRoomIdRoute
  ApiPublicHooksCleanupRoute: typeof ApiPublicHooksCleanupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId': {
      id: '/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof RoomRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/cleanup': {
      id: '/api/public/hooks/cleanup'
      path: '/api/public/hooks/cleanup'
      fullPath: '/api/public/hooks/cleanup'
      preLoaderRoute: typeof ApiPublicHooksCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CreateRoute: CreateRoute,
  HowItWorksRoute: HowItWorksRoute,
  JoinRoute: JoinRoute,
  RoomRoomIdRoute: RoomRoomIdRoute,
  ApiPublicHooksCleanupRoute: ApiPublicHooksCleanupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
